firefly-iii/firefly-iii

app/database/migrations/2014_12_13_190730_changes_for_v321.php, app/database/migrations/2014_12_24_191544_changes_for_v322.php
Installation fails without these changes
=> Handle foreign keys

app/Http/Controllers/CategoryController.php, app/Http/Controllers/GoogleChartController.php, app/Models/Account.php
– Chart fix for accounts with accented letters
– Fix for account creation in firstOrCreateEncrypted()
– Removed merge conflict from CategoryController
=> Fixes for chart and account creation

app/Http/Controllers/HomeController.php, resources/views/index.blade.php
Display the total amount of savings on dashboard widget.
=> Add savings total for savings widget on dashboard

app/Handlers/Events/UpdateJournalConnection.php, app/Helpers/Collection/Bill.php, app/Helpers/Collection/Category.php, app/Helpers/Collection/Expense.php, app/Helpers/Collection/Income.php, app/Helpers/Report/ReportHelper.php, app/Helpers/Report/ReportQuery.php, app/Http/Controllers/AccountController.php, app/Http/Controllers/Auth/AuthController.php, app/Http/Controllers/BillController.php, app/Http/Controllers/BudgetController.php, app/Http/Controllers/CurrencyController.php, app/Http/Controllers/PiggyBankController.php, app/Http/Controllers/TransactionController.php, app/Http/Middleware/Cleanup.php, app/Http/breadcrumbs.php
@JC5 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/JC5/firefly-iii/
=> Scrutinizer Auto-Fixes

resources/twig/partials/control-bar.twig
Removed duplicate control bar item "new_revenue_account"
=> Removed duplicated controlbar item

.gitignore, app/Helpers/Csv/Data.php, app/Http/Controllers/CsvController.php, resources/lang/en_US/firefly.php, resources/lang/en_US/form.php, resources/lang/nl_NL/firefly.php, resources/lang/nl_NL/form.php, resources/views/csv/index.twig
Improved pull request, based on the develop branch. See also https://github.com/JC5/firefly-iii/pull/143
=> Option to choose CSV delimiter when importing data

app/Providers/FireflyServiceProvider.php, app/Repositories/Account/AccountRepository.php
This solves a bug when saving a new RuleGroup
=> Added binding for RuleGroupRepositoryInterface

app/Http/Controllers/PreferencesController.php, resources/lang/en_US/firefly.php, resources/lang/nl_NL/firefly.php, resources/views/preferences/index.twig
Hi,
I am starting over with 2 factor auth.
In this PR I added the setting to enable 2fa in the preferences page. 
The  next step I would like to implement is to redirect the user to another page to validate the QR code if the user enables the setting.
=> Started over with 2fa

public/js/guest.js, resources/views/layout/default.twig, resources/views/layout/empty.twig, resources/views/layout/guest.twig
Hi, some files did not respect the base url
Also, I like that the first input field in a form automatically receives the focus, so I added that to the guest area.
=> Some small fixes to respect the base url

app/Http/Controllers/AccountController.php, app/Repositories/Account/AccountRepository.php, resources/lang/en_US/form.php, resources/lang/nl_NL/form.php, resources/views/accounts/create.twig, resources/views/accounts/edit.twig
Hi,
I tried to start with implementing #107.
I added the field account number besides the IBAN, couldn't determine from the issue text the desired behaviour.
Only creating/editig an account with an account number works for now.
=> Tried to start with #107

app/Rules/Actions/ActionFactory.php, app/Rules/Processor.php, app/Rules/Triggers/TriggerFactory.php
This enables reuse of the logic of creating actions and triggers
=> Introduction of factories to create rule actions and rule triggers

app/Helpers/Csv/Specifix/AbnAmroDescription.php
Some specific types of descriptions used by ABNAMRO normally include a more detailed description inside. However, sometimes this description is not provided. In those cases, a detailed description is created from information that is provided.
=> Bugfix in parsing specific descriptions

public/js/reports/default/month.js, public/js/reports/default/reports.js
=> Revert "Fix use of absolute URLs for linecharts for the report pages."

resources/lang/en_US/help.php
This time using the correct branch :smile:
=> Fixed small typo.

app/Repositories/Bill/BillRepository.php
Some parentheses were missing :)
=> Fixed incorrect average of expectedAmount in active bills.

config/firefly.php, database/seeds/TransactionCurrencySeeder.php
=> add brazilian currency and translation

.env.example, .env.testing, app/Providers/AppServiceProvider.php
Hi,
I created a quick fix for issue #181 to force https based on an app setting in .env
=> Force https schema if APP_FORCE_SSL=true in .env

app/Support/Steam.php
As a follow up from #284, make room for case insensitive and abnormally large php.ini (like mine)
=> Generalise Steam::phpBytes

app/Import/Converter/Description.php, app/Import/Specifics/IngDescription.php, config/csv.php
Hi,
I dont know if you want to merge it. I've created a Specifics file for the description field in the ING CSV files.
In some occasions the IBAN and Name is included in the description field.
And for Betaalautomaat betalingen the description is very cryptic.
So I've removed the IBAN and Name from the description and added the name for bestaalautomaat betalingen so you can see in de description which store the payment was.
Feel free to ask if you have any questions.
PS this is my first pull request
=> ING Import

Dockerfile
fixes #521 for docker environment
=> add firefly locales to Dockerfile

app/Models/PiggyBank.php, app/Support/Twig/PiggyBank.php, resources/views/piggy-banks/show.twig
If a piggybank has both a target date and a target amount, show how much money needs to be added to the piggybank each month to achieve both targets.
Strings are currently hard-coded because I want to gauge the reaction to this :)
=> Show suggested monthly savings for a piggybank

resources/lang/en_US/firefly.php, resources/views/piggy-banks/show.twig
PR #594 introduced suggested savings, this PR makes the text translatable.
=> Make suggested savings text translatable

app/Support/Search/Search.php
=> Fix search that worked only for lowercase queries

app/Http/Controllers/RuleController.php
=> Fix reseting action type when editing rule

resources/lang/en_US/firefly.php, resources/views/search/index.twig
=> Add missing translations strings in search

app/Import/Specifics/SnsDescription.php, config/csv.php
Very basic specifics code for removing quotes from start and end of descriptions.
=> Added SNS specifics code for removing quotes from description

.htaccess
- To force HTTPS
- To hide directory listing
- To prevent access to .env and other files
@JC5
=> create .htaccess file

app/Import/Routine/BunqRoutine.php
=> iban returned from bunq might be empty.

app/Support/Import/Configuration/Bunq/HaveAccounts.php, resources/views/import/bunq/accounts.twig
Fixes #1398 
- Make the selectionBox to select the matching IBAN number when importing.
@JC5
=> Select the matching bunq account from the import. Fixes #1398

database/seeds/TransactionCurrencySeeder.php
Adding Indian rupee under asian currencies.
Indian rupee and symbol added.
- 
- 
- 
@JC5
=> Adding Indian rupee

.gitignore, Dockerfile
References #1443 (if relevant)
- Updates curl in docker file.
@JC5
=> Update curl in docker firefly-iii/firefly-iii#1443

readme.md
As the link was changed, the current link was broken. So fixed it.
@JC5
=> Change in YunoHost links

database/seeds/TransactionCurrencySeeder.php
=> Add ILS currency

app/Console/Commands/CreateExport.php, app/Console/Commands/EncryptFile.php, app/Export/ExpandedProcessor.php, app/Export/Exporter/CsvExporter.php, app/Helpers/Attachments/AttachmentHelper.php, app/Repositories/Attachment/AttachmentRepository.php, app/Repositories/ExportJob/ExportJobRepository.php, app/Services/Internal/File/EncryptService.php, tests/Unit/Helpers/Attachments/AttachmentHelperTest.php
Related to #1727 (if relevant)
- fix local references in upload/export disk
@JC5
=> fix local references in upload/export disk. first step for #1727.

app/Support/FinTS/MetadataParser.php, app/Support/Import/Routine/FinTS/StageImportDataHandler.php, tests/Unit/Support/FinTS/MetadataParserTest.php
See #1159 
- Try to parse description during FinTS import
@JC5
=> Parse description from FinTSTransaction

composer.json, composer.lock, config/filesystems.php
- working with previous fallback-adapter version - not violating the internal guarantee
- bugfix in export local disk
- prefer local to remote
@JC5
=> Fix remote backing storage

database/seeds/TransactionCurrencySeeder.php
#1847 
- Added swiss franc to currency seeder
@JC5
=> Add swiss franc to currency seeder

resources/views/v1/import/fints/new.twig
Fixes #1868
- Username for FinTS import is not mandatory. 
@JC5
=> Username for FinTS import is not mandatory.

resources/views/v1/recurring/create.twig, resources/views/v1/recurring/edit.twig
Should be good now 👍 
- Fixed fullcalendar.min.js link in edit.twig
- Fixed fullcalendar.min.js link in create.twig
@JC5
=> Fix fullcalendar.min.js links

database/seeds/TransactionCurrencySeeder.php
- Added Croatian kuna to currency seeder
@JC5
=> Add Croatian kuna to currency seeder

.env.docker, .env.example, .env.heroku, .env.sandstorm, .env.testing, app/Providers/FireflyServiceProvider.php, app/Services/Currency/RatesApiIOv1.php, config/firefly.php
Implements #1947 enhancement
- Implemented multiple Currency Exchange Rates sites engine
- Updated .env.X config files with new settings
@JC5
=> Implemented multiple Currency Exchange Rates sites engine

public/v1/js/ff/charts.js
- Removed `console.log` statement in js code
@JC5
=> Remove console.log statement

database/migrations/2018_09_05_195147_changes_for_v477.php
Fixes issue #2125 maybe
- rollback implementation for migration 477
@JC5
=> add missing rollback for 477 migration

readme.md
- Replace "you're" with "your".
=> docs: Fix minor typo

.github/ranger.yml, readme.md
=> Fix ranger.yml config

app/Repositories/Budget/BudgetRepository.php
Fixes issue #2443
- Updated the indexes in BudgetRepository to match the fields of the API
I am **really** not sure this is a correct solution. While the POST call now works, I did not expected the GUI to work too, as  I believed they would share the same code path.
But to my surprise this doesn't break the GUI so I'm submitting this in case this is correct.
@JC5
=> Fix wrong indexes in BudgetRepository

resources/views/v1/list/groups.twig
Used to be there previously (at least at 4.7.8). Used in my automation.
Similar to other views: https://github.com/firefly-iii/firefly-iii/search?q=data-date&unscoped_q=data-date
- 
- 
- 
@JC5
=> Add date attribute to the list row

.env.example, config/services.php
Fixes issue #2612
- move MAILGUN endpoint into config file
=> Configuragble Mailgun endpoint

app/Api/V1/Requests/AccountUpdateRequest.php, app/Api/V1/Requests/AttachmentStoreRequest.php, app/Api/V1/Requests/AttachmentUpdateRequest.php, app/Api/V1/Requests/BillRequest.php, app/Api/V1/Requests/PiggyBankRequest.php, app/Api/V1/Requests/RecurrenceUpdateRequest.php, app/Api/V1/Requests/Request.php, app/Api/V1/Requests/TransactionLinkRequest.php, app/Api/V1/Requests/TransactionStoreRequest.php, app/Http/Requests/Request.php
Fixes issue #2629 (partly, was already mostly fixed)
- API object's notes fields now correctly preserve newlines.
@JC5
=> Additional fix for #2629 with API

app/Http/Requests/AccountFormRequest.php
Fixes issue #2629 (partly, most of it is already fixed)
- Account's notes field now correctly preserve newlines.
@JC5
=> Additional fix for #2629 with accounts

public/v1/js/ff/import/status_v2.js, resources/views/v1/import/status.twig
As discussed, separate PR for cleanup.
Regards,
Melroy
=> Clean-up only

app/Http/Controllers/Chart/ReportController.php
Fix issue #3027 by filtering the transaction types included in the report.
=> Fix issue 3027

app/Rules/UniqueIban.php
=> Fixes #2998

app/Http/Controllers/Json/AutoCompleteController.php, routes/web.php
=> Add missing function that resulted in 404's.

readme.md
=> Write new readme.

resources/lang/en_US/firefly.php, resources/views/v1/layout/default.twig, resources/views/v1/partials/menu-sidebar.twig
It's related to the issue #3277
- Reordered and grouped some items in the sidebar menu according to their frequency of use and to encourage the use of them
@JC5
=> Menu reordering

app/Http/Controllers/Budget/AvailableBudgetController.php, app/Http/Controllers/Budget/BudgetLimitController.php, app/Http/Controllers/Budget/CreateController.php, app/Http/Controllers/Budget/DeleteController.php, app/Http/Controllers/Budget/EditController.php, app/Http/Controllers/Budget/IndexController.php, app/Http/Controllers/Budget/ShowController.php, app/Http/Controllers/Category/CreateController.php, app/Http/Controllers/Category/DeleteController.php, app/Http/Controllers/Category/EditController.php, app/Http/Controllers/Category/IndexController.php, app/Http/Controllers/Category/NoCategoryController.php, app/Http/Controllers/Category/ShowController.php, app/Http/Controllers/Json/BudgetController.php, app/Http/Controllers/PiggyBankController.php, app/Http/Controllers/ReportController.php, app/Http/Controllers/TagController.php, resources/views/v1/accounts/reconcile/transactions.twig, resources/views/v1/index.twig, resources/views/v1/partials/control-bar.twig, resources/views/v1/popup/list/journals.twig, resources/views/v1/reports/partials/journals-audit.twig
Fixes issue #3322
- Update Budgets pages and block
- Update Piggy Banks pages
- Update Categories pages and block
- Update Tags pages
- Update Reports pages
@JC5
=> Update the pages and blocks icons

app/Http/Controllers/Transaction/ShowController.php, resources/views/v1/transactions/show.twig
Fixes #3409
Not sure getAccounts is the best implementation - feel free to suggest how to improve it!
=> Display account names only once when displaying split transactions

public/v1/js/ff/accounts/reconcile.js
First try was #3424
Found an issue when a transaction is already (un)checked and you (un)check the "select all" button: the amount was added (subtracted) a second time to the balance.
=> Fix reconcile difference

resources/lang/en_US/firefly.php, resources/views/v1/budgets/index.twig
=> Translations tweaks

resources/lang/en_US/firefly.php, resources/views/v1/debug.twig
Only instructions are translated, debug info are left untouched so that we don't receive exotic bug reports. :-)
=> Translate debug page

app/Api/V1/Controllers/Search/TransactionController.php
- Transaction search api implemented using mostly the same process as the
existing search functionality.
@JC5
=> Added transaction search api support

app/Api/V1/Requests/AccountStoreRequest.php, app/Api/V1/Requests/AccountUpdateRequest.php
Fixes issue #3564
Fixed typo in `cc_Monthly_payment_date`.
@JC5
=> Fix update monthly_payment_date using the API

resources/assets/js/locales/en.json
Spotted by Luca90 on Crowdin
https://crowdin.com/translate/firefly-iii/all/en-fr#10916
=> Fix copy/paste error

readme.md
Old one doesn't work when clicked
=> Fix anchor link

app/Helpers/Collector/Extensions/MetaCollection.php
Hi!
After upgrading to 5.4.10 I encoutered a error when creating new transactions via API.
Example Request:
<details>
<summary>Click to expand!</summary>
```
curl --location --request POST 'https://firefly.yourdomain.com/api/v1/transactions' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer YOUR TOKEN' \
--data-raw '{
"transactions": [
{
"type": "deposit",
"date": "2019-09-17",
"amount": 12.95,
"description": "Vegetables",
"category_name": "Groceries",
"source_name": "Test",
"destination_name": "Geldbörse"
}
]
}'
```
</details>
Error logs:
<details>
<summary>Click to expand!</summary>
```
[2020-09-22 23:31:09] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notes' in 'where clause' (SQL: select …
```
=> Fixes `Unknown column 'notes' in 'where clause'` when using Rules

readme.md
- add travis build badge, preview here https://github.com/lastlink/firefly-iii/tree/patch-4
@JC5
=> add travis build badge

readme.md
Tiny fix for the index in the readme. Tried removing the space from the target header as well, but that breaks the image.
@JC5
=> Fix link in index

resources/views/v1/auth/mfa.twig, resources/views/v2/auth/mfa.twig
Autocomplete is not useful since codes change every 30 seconds.
@JC5
=> Disable autcomplete for 2FA field

app/Helpers/Collector/Extensions/MetaCollection.php, app/Helpers/Collector/GroupCollectorInterface.php, app/Support/Search/OperatorQuerySearch.php, config/firefly.php, public/v1/js/ff/rules/create-edit.js, resources/lang/en_US/firefly.php
Related to https://github.com/firefly-iii/firefly-iii/issues/5606 / https://github.com/firefly-iii/firefly-iii/issues/5326 / https://github.com/firefly-iii/firefly-iii/issues/4903
- Adds rules/search support for presence/absence of the `external_url` field.
Todo:
@JC5 Are you open to this change?
=> Attempt to add `external_url` filtering support

.env.example, config/database.php
This just adds the ability to set a redis username.
=> Add username to fit redis 6+ ACL capabilities

readme.md
=> Add badge.

app/Support/Http/Controllers/GetConfigurationData.php, resources/lang/en_US/firefly.php
Hello, we are a group of students that had to work on an issue/feature request as a part of our course. We chose to work on your project and here is what we did if you are interested in using it. 
We saw that you implement a new layout in vue so maybe you want the fix to be implemented in vue as well? Write us a comment if you want us to fix that. 
Fixes issue #5234
- Added option for the beginning of the month to the current date and from the beginning of the year to the current date.
- All translations should be in English per your instructions.
@JC5
=> Issue #5234 fix 

app/Helpers/Collector/Extensions/MetaCollection.php, app/Support/Search/OperatorQuerySearch.php, config/search.php, resources/lang/en_US/firefly.php
- Allow searching for the SEPA CT
- Allow rules matching the SEPA CT
@JC5
=> Add search support for SEPA CT

app/Support/Authentication/RemoteUserGuard.php
=> Also pick email address from apache filtered headers

app/Http/Kernel.php, app/Http/Middleware/AcceptHeaders.php
=> Fix https://github.com/firefly-iii/firefly-iii/issues/6829

app/Api/V1/Controllers/System/UserController.php, app/Http/Middleware/Authenticate.php, changelog.md
=> Expand authentication validation in API.

app/Console/Commands/Upgrade/UpgradeLiabilitiesEight.php, app/Http/Requests/AccountFormRequest.php, app/Services/Internal/Support/CreditRecalculateService.php, app/Services/Internal/Update/AccountUpdateService.php, app/Validation/Api/Data/Bulk/ValidatesBulkTransactionQuery.php, changelog.md, public/v1/js/ff/accounts/create.js, public/v1/js/ff/accounts/edit.js, resources/lang/en_US/firefly.php, resources/views/accounts/create.twig, resources/views/accounts/edit.twig
=> Fix liabilities

app/Http/Middleware/Authenticate.php, app/Support/Authentication/RemoteUserGuard.php
=> Add debug for https://github.com/firefly-iii/firefly-iii/issues/6831

resources/assets/js/components/transactions/CreateTransaction.vue, resources/assets/js/components/webhooks/Create.vue, resources/assets/js/components/webhooks/Edit.vue, resources/assets/js/components/webhooks/Show.vue
=> Fix improper escape.

app/Api/V1/Requests/Models/Account/StoreRequest.php, app/Api/V1/Requests/Models/Account/UpdateRequest.php
Fixes issue #6869 (if relevant)
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/6869

app/Http/Controllers/Json/RecurrenceController.php
=> Validate date field.

routes/web.php
=> Add regular expressions to routes.

routes/web.php
=> Fix dateformat.

routes/api-noauth.php, routes/api.php, routes/breadcrumbs.php, routes/channels.php, routes/web.php
=> Cleanup routes and code.

app/Api/V1/Controllers/Controller.php, app/Api/V2/Controllers/Controller.php, app/Http/Controllers/SearchController.php, app/Http/Requests/ReportFormRequest.php, app/Support/Authentication/RemoteUserGuard.php, app/Support/Request/ConvertsDataTypes.php, app/Support/Search/OperatorQuerySearch.php
=> Catch various validation errors

app/Support/Request/ConvertsDataTypes.php
=> Add some extra catches and remove debug info

.github/mergify.yml
=> no message

app/Api/V1/Controllers/Controller.php, app/Api/V1/Controllers/Data/DestroyController.php, app/Api/V1/Controllers/Models/TransactionCurrency/DestroyController.php, app/Api/V1/Controllers/Webhook/AttemptController.php, app/Api/V1/Controllers/Webhook/DestroyController.php, app/Api/V1/Controllers/Webhook/MessageController.php, app/Api/V2/Controllers/Controller.php, app/Console/Commands/Correction/FixTransactionTypes.php, app/Console/Commands/Export/ExportData.php, app/Console/Commands/VerifiesAccessToken.php, app/Rules/IsValidAttachmentModel.php, app/Validation/CurrencyValidation.php
=> Catch and verify various errors

frontend/src/components/dashboard/AccountChart.vue, frontend/src/components/dashboard/SpendInsightBox.vue, frontend/src/layouts/MainLayout.vue, frontend/src/pages/dashboard/Dashboard.vue
=> Better boxes in v3

.env.example, config/firefly.php
=> Remove env

app/Repositories/Rule/RuleRepository.php
=> Fix issue with rule repository validation

app/Api/V1/Controllers/Models/TransactionCurrency/DestroyController.php, app/Api/V1/Controllers/Models/TransactionLinkType/StoreController.php, app/Api/V1/Controllers/Models/TransactionLinkType/UpdateController.php, app/Api/V1/Controllers/System/ConfigurationController.php
=> Switch to validation style error in API

composer.lock, public/v1/lib/adminlte/css/skins/skin-dark.css
=> Fix CSS and update packages.

app/Validation/Administration/ValidatesAdministrationAccess.php
=> Fix https://github.com/firefly-iii/firefly-iii/issues/6947

app/Console/Commands/Integrity/CreateGroupMemberships.php
=> Always (try to) create group

app/Services/Webhook/StandardWebhookSender.php
=> Fix missing message call.

.github/mergify.yml
=> Better mergify rules.

app/Services/Internal/Support/JournalServiceTrait.php
=> Null check for https://github.com/firefly-iii/firefly-iii/issues/6834

composer.json, composer.lock
=> Downgrade phpunit due to laravel's incompatibility.

.github/workflows/build.yml
=> Add qodana.

.github/workflows/build.yml, .github/workflows/qodana.yaml
=> Add new jpbs

.github/workflows/qodana.yml
=> Rename and cleanup file.

app/Http/Controllers/PreferencesController.php
=> Fix issue with preferences object.

changelog.md
=> Write changelog.

.ci/phpstan.sh, app/Support/Search/OperatorQuerySearch.php
=> Restore missing method.

app/Api/V1/Requests/Insight/GenericRequest.php
Fixes issue #7020
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7020

app/Factory/TransactionCurrencyFactory.php, app/Services/Internal/Update/CurrencyUpdateService.php
=> Catch escape in currencies

app/Http/Controllers/Bill/IndexController.php
=> Add missing indexes.

app/Api/V1/Controllers/Models/Account/ListController.php, app/Api/V1/Controllers/Models/AvailableBudget/ShowController.php, app/Api/V1/Controllers/Models/Budget/ListController.php, app/Api/V1/Controllers/Models/ObjectGroup/ListController.php, app/Api/V1/Controllers/Models/PiggyBank/ListController.php, app/Api/V1/Controllers/Models/PiggyBank/ShowController.php, app/Api/V1/Controllers/Models/RuleGroup/ListController.php, app/Api/V1/Controllers/Models/RuleGroup/ShowController.php, app/Api/V1/Controllers/Models/RuleGroup/TriggerController.php, app/Api/V1/Controllers/Models/Transaction/ListController.php, app/Api/V1/Controllers/Models/TransactionCurrency/ListController.php, app/Api/V1/Controllers/Models/TransactionLink/ShowController.php, app/Api/V1/Controllers/Models/TransactionLinkType/ShowController.php
=> Fix routes in https://github.com/orgs/firefly-iii/discussions/7035

app/Factory/TransactionFactory.php, app/Factory/TransactionJournalFactory.php, app/Services/Internal/Support/AccountServiceTrait.php, app/Services/Internal/Support/JournalServiceTrait.php
=> Will update IBAN in existing account if necessary and/or possible.

routes/breadcrumbs.php
=> Fix bad routes

app/Http/Controllers/DebugController.php, resources/views/debug.twig
=> Add max upload size to debug page.

.github/workflows/qodana.yml, qodana.yaml
=> Add IDE helper script.

qodana.yaml
=> Ignore errors in ide_helper

.github/workflows/build.yml, .github/workflows/closed-issues.yml, .github/workflows/depsreview.yaml, .github/workflows/laravel.yml, .github/workflows/lock.yml, .github/workflows/stale.yml
=> Update various actions

app/Http/Controllers/Bill/IndexController.php, app/Services/Internal/Update/RecurrenceUpdateService.php
=> Missing indexes

app/Http/Controllers/System/InstallController.php, app/Repositories/Tag/TagRepository.php, app/Support/Http/Controllers/CreateStuff.php, public/v1/css/firefly.css, resources/assets/js/components/transactions/CustomTransactionFields.vue
=> Various code cleanup, see if Qodana picks them up

.github/workflows/cleanup.yml
=> Update prune workflow.

app/Support/Logging/AuditProcessor.php
=> Fix audit processor

app/Services/Internal/Update/JournalUpdateService.php
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7083

resources/lang/en_US/config.php
=> Date fix for https://github.com/firefly-iii/firefly-iii/issues/7079

resources/views/accounts/show.twig, resources/views/index.twig
=> Fix broken chart

app/Repositories/PiggyBank/ModifiesPiggyBanks.php
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7093

frontend/quasar.conf.js, public/v3-local/css/fonts.css, resources/views/layout/v3/session.twig
=> CSS fixes for subdirectories. Full credits to @GaneshKandu

app/Services/FireflyIIIOrg/Update/UpdateRequest.php
Fixes issue #7112 (if relevant)
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7112

app/Jobs/MailError.php
=> Catch common mail errors

public/v1/js/ff/accounts/index.js, public/v1/js/ff/firefly.js
Fixes issue #7131 (if relevant)
- 
- 
- 
@JC5
=> Fix #7131 by expanding the global ajaxSetup instructions.

config/mail.php
=> Make sure default mail provider is "log", not smtp

app/Http/Middleware/AcceptHeaders.php
Fixes issue #7140 (if relevant)
- 
- 
- 
@JC5
=> Fix #7140 by better validating header content.

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/fr.yml
=> Small issue template updates

app/Validation/Account/WithdrawalValidation.php, app/Validation/CurrencyValidation.php, app/Validation/GroupValidation.php, app/Validation/TransactionValidation.php, resources/lang/en_US/validation.php
Fixes issue #7124 (if relevant)
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7124

resources/assets/js/components/transactions/Bill.vue, resources/assets/js/components/transactions/Budget.vue
Fixes issue #7165 (if relevant)
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7165

public/v1/js/ff/transactions/show.js
Fixes issue #7192 (if relevant)
- 
- 
- 
@JC5
=> Extra code for #7192

app/Validation/TransactionValidation.php
Fixes issue #7214 (if relevant)
- 
- 
- 
@JC5
=> Possible fix for #7214

resources/assets/js/components/form/WebhookDelivery.vue, resources/assets/js/components/form/WebhookResponse.vue, resources/assets/js/components/form/WebhookTrigger.vue
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7227

bootstrap/app.php
=> Drop bc scale

database/migrations/2016_06_16_000002_create_main_tables.php, database/migrations/2016_12_22_150431_changes_for_v430.php, database/migrations/2017_04_13_163623_changes_for_v440.php, database/migrations/2017_06_02_105232_changes_for_v450.php, database/migrations/2018_06_08_200526_changes_for_v475.php, database/migrations/2019_12_28_191351_make_locations_table.php, database/migrations/2020_03_13_201950_changes_for_v520.php
=> Better accuracy for database. Does not affect current users.

app/Api/V2/Controllers/Autocomplete/AccountController.php, app/Api/V2/Controllers/Controller.php, app/Api/V2/Request/Autocomplete/AutocompleteRequest.php, app/Models/UserGroup.php, app/Providers/AccountServiceProvider.php, app/Repositories/Administration/Account/AccountRepository.php, app/Repositories/Administration/Account/AccountRepositoryInterface.php, app/Support/Repositories/Administration/AdministrationTrait.php, frontend/src/api/v2/autocomplete/accounts.js, frontend/src/boot/axios.js, frontend/src/components/transactions/Split.vue, frontend/src/components/transactions/form/SourceAccount.vue, frontend/src/components/transactions/form/TransactionDescription.vue, frontend/src/pages/transactions/Create.vue, routes/api.php
=> Ac accounts

app/TransactionRules/Actions/AppendDescriptionToNotes.php, app/TransactionRules/Actions/ConvertToDeposit.php, app/TransactionRules/Actions/ConvertToTransfer.php, app/TransactionRules/Actions/ConvertToWithdrawal.php, app/TransactionRules/Actions/MoveNotesToDescription.php, config/firefly.php
=> Fix bad rule action

app/Console/Commands/Integrity/CreateGroupMemberships.php, app/Support/Authentication/RemoteUserGuard.php, app/Support/Authentication/RemoteUserProvider.php
Fixes issue #7278 (if relevant)
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7278

app/Jobs/MailError.php
=> Mail error

app/Services/Internal/Support/JournalServiceTrait.php, config/firefly.php
=> Fix issue with opposing account creation

app/Models/UserGroup.php, app/Repositories/PiggyBank/ModifiesPiggyBanks.php
Fixes issue #7308 (if relevant)
- 
- 
- 
@JC5
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7308

config/mail.php
=> Better defaults for email.

app/Http/Controllers/HomeController.php, database/migrations/2016_06_16_000000_create_support_tables.php, database/migrations/2016_06_16_000002_create_main_tables.php, database/migrations/2022_08_21_104626_add_user_groups.php, database/migrations/2022_09_18_123911_create_notifications_table.php, database/migrations/2022_10_01_074908_invited_users.php, database/migrations/2022_10_01_210238_audit_log_entries.php
=> Various improved error catching.

app/Http/Controllers/Controller.php, app/Http/Controllers/PreferencesController.php, config/firefly.php, resources/lang/en_US/firefly.php, resources/views/layout/default.twig, resources/views/layout/empty.twig, resources/views/layout/guest.twig, resources/views/preferences/index.twig
=> Dark mode button

app/Console/Commands/ForceDecimalSize.php
=> Add decimal command.

app/Console/Commands/ForceDecimalSize.php, app/Console/Commands/ForceMigration.php
=> Add commit call to force the commands to go through.

frontend/src/App.vue
=> Redirect when unauthenticated.

resources/views/emails/bill-warning.blade.php
=> Fix date fields

app/Http/Controllers/System/InstallController.php, public/v1/js/ff/install/index.js, resources/views/install/index.twig, resources/views/layout/install.twig
=> Fix installer

app/Support/Search/OperatorQuerySearch.php
Fixes issue #7377 (if relevant)
- 
- 
- 
@JC5
=> Another fix for #7377

app/Console/Commands/System/UpgradeFireflyInstructions.php
=> Fix method name

app/Console/Commands/Upgrade/UpgradeDatabase.php
=> Remove duplicate commands.

app/Http/Requests/BillUpdateRequest.php, resources/views/emails/error-html.twig
=> Add rule for notes and better escaping in errors.

app/Api/V1/Requests/Models/Transaction/StoreRequest.php, app/Api/V1/Requests/Models/Transaction/UpdateRequest.php, app/Http/Requests/MassEditJournalRequest.php, app/Validation/GroupValidation.php, app/Validation/TransactionValidation.php, resources/lang/en_US/validation.php
=> Fix length validation

app/Http/Requests/TagFormRequest.php
=> Add validation check.

app/Api/V1/Controllers/Controller.php, app/Http/Middleware/Authenticate.php
=> Remove debug logging.

app/Api/V1/Controllers/Controller.php, app/Events/Model/BudgetLimit/Created.php, app/Events/Model/BudgetLimit/Deleted.php, app/Events/Model/BudgetLimit/Updated.php, app/Handlers/Events/Model/BudgetLimitHandler.php, app/Http/Controllers/Budget/BudgetLimitController.php, app/Http/Controllers/Budget/IndexController.php, app/Models/BudgetLimit.php, app/Providers/EventServiceProvider.php, composer.json, composer.lock, resources/views/budgets/index.twig
=> Better management and calculation of available budgets.

app/Handlers/Events/Model/BudgetLimitHandler.php
=> Remove dangerous eternal loop

app/Http/Controllers/Json/BudgetController.php
=> Fix division by zero

app/Console/Commands/Correction/FixIbans.php
=> Don't trigger on empty ibans.

app/Http/Controllers/System/HealthcheckController.php
=> Change health endpoint to include a DB check.

resources/views/auth/mfa.twig
- multi factor authentication input field was updated to be automatically focused on page load.
@JC5
=> Focus on MFA input field on page load

app/Console/Commands/System/CreateFirstUser.php, app/Console/Commands/System/ForceDecimalSize.php, database/migrations/2020_07_24_162820_changes_for_v540.php, database/migrations/2020_11_12_070604_changes_for_v550.php, database/migrations/2021_03_12_061213_changes_for_v550b2.php, database/migrations/2021_08_28_073733_user_groups.php, database/migrations/2022_08_21_104626_add_user_groups.php
=> Fix decimals command expanded.

app/Http/Middleware/Installer.php
=> Remove logging

app/Console/Commands/Correction/FixPiggies.php, app/Factory/PiggyBankEventFactory.php, app/Factory/TransactionJournalFactory.php, app/TransactionRules/Actions/UpdatePiggybank.php, resources/assets/js/components/transactions/PiggyBank.vue
Fixes issue # 6631
- Added ability to deduct from a Piggy Bank on a Withdrawal
- Added ability to add to Piggy Bank from a Deposit
@JC5
The feature to add to a Piggy Bank from a Deposit was not a part of the original issue but when implementing it seemed to make sense to do it at the same time. If you would like me to make it only for Withdrawals let me know and I can change that.
=> Withdraw from piggy banks

app/Services/Internal/Support/RecurringTransactionTrait.php, app/Support/Request/GetRecurrenceData.php, app/Validation/RecurrenceValidation.php, resources/views/recurring/show.twig
=> Fix https://github.com/firefly-iii/firefly-iii/issues/7588

app/Console/Commands/Upgrade/AccountCurrencies.php, app/Console/Commands/Upgrade/AppendBudgetLimitPeriods.php, app/Console/Commands/Upgrade/BackToJournals.php, app/Console/Commands/Upgrade/BudgetLimitCurrency.php, app/Console/Commands/Upgrade/CCLiabilities.php, app/Console/Commands/Upgrade/MigrateAttachments.php, app/Console/Commands/Upgrade/MigrateJournalNotes.php, app/Console/Commands/Upgrade/MigrateRecurrenceMeta.php, app/Console/Commands/Upgrade/MigrateRecurrenceType.php, app/Console/Commands/Upgrade/MigrateTagLocations.php, app/Console/Commands/Upgrade/MigrateToRules.php, app/Console/Commands/Upgrade/OtherCurrenciesCorrections.php, app/Console/Commands/Upgrade/RenameAccountMeta.php, app/Console/Commands/Upgrade/TransactionIdentifier.php, app/Console/Commands/Upgrade/TransferCurrenciesCorrections.php, app/Console/Commands/Upgrade/UpgradeLiabilities.php, app/Console/Commands/Upgrade/UpgradeLiabilitiesEight.php, app/Console/Commands/Upgrade/UpgradeSkeleton.php.stub
=> chore: fix command output

.env.example
Fixes issue #7580
- amend links in `.env.example` to point to correct documentation pages
@JC5
=> Fix URLs in .env.example #7580

app/Services/Internal/Update/RecurrenceUpdateService.php
=> fix: extra bracket breaks code.

app/Api/V1/Controllers/Autocomplete/AccountController.php, app/Api/V1/Controllers/Chart/AccountController.php, app/Api/V1/Controllers/Search/AccountController.php, app/Api/V2/Controllers/Autocomplete/AccountController.php, app/Console/Commands/Upgrade/AccountCurrencies.php, app/Factory/AccountFactory.php, app/Http/Controllers/Report/AccountController.php, app/Http/Middleware/AcceptHeaders.php, app/Models/Account.php, app/Models/AccountMeta.php, app/Repositories/Account/AccountRepository.php, app/Repositories/Account/AccountTasker.php, app/Services/Internal/Support/AccountServiceTrait.php, app/Services/Internal/Update/AccountUpdateService.php, app/Support/Form/AccountForm.php, app/Support/Search/AccountSearch.php, app/TransactionRules/Factory/ActionFactory.php, app/Validation/AccountValidator.php, database/migrations/2020_11_12_070604_changes_for_v550.php, qodana.yaml
=> chore: fix various qodana issues

qodana.yaml
=> fix qodana yaml

app/Console/Commands/System/UpgradeFireflyInstructions.php
=> feat: Expand logo in startup scripts

resources/views/form/amount-no-currency.twig, resources/views/form/checkbox.twig, resources/views/form/date.twig, resources/views/form/file.twig, resources/views/form/integer.twig, resources/views/form/object_group.twig, resources/views/form/password.twig, resources/views/form/percentage.twig, resources/views/form/select.twig, resources/views/form/text.twig, resources/views/form/textarea.twig
=> fix: expand form elements with ID

app/Console/Commands/System/UpgradeFireflyInstructions.php
=> chore: tune the logo

app/Console/Commands/System/UpgradeFireflyInstructions.php
=> Another small tune

app/Http/Controllers/ProfileController.php
=> Fix: missing variable

app/Validation/Account/DepositValidation.php, app/Validation/Account/TransferValidation.php, app/Validation/Account/WithdrawalValidation.php, resources/lang/en_US/validation.php
=> Fix account validation

app/Support/Navigation.php, tests/unit/Support/NavigationAddPeriodTest.php, tests/unit/Support/NavigationStartOfPeriodTest.php
Just continue the work to increase the coverage of Navigation class
@JC5
=> Cover the startOfPeriod method of Navigation class

app/Api/V1/Controllers/System/CronController.php
- exchangeRatesCronJob should only be fired when ENABLE_EXTERNAL_RATES is true
=> Fix Cron job bug

app/Services/Internal/Support/CreditRecalculateService.php
Withdrawal from liability to expense account currently fall in all other case, which decrease the debt. This can be interest payment, so I added a case to increase de debt for this type of transaction.
@JC5
=> Fix interest payment deducted from amount due

app/Repositories/Rule/RuleRepository.php
Fixes issue https://github.com/firefly-iii/firefly-iii/issues/8069
- During the refactoring the description field was lost. Now, I update the RuleRepositories->store function with right code for description field.
@JC5
=> [Issue #8069] Fixed bug on description field

tests/unit/Support/NavigationPreferredCarbonFormatByPeriodTest.php, tests/unit/Support/NavigationPreferredCarbonFormatTest.php, tests/unit/Support/NavigationPreferredEndOfPeriodTest.php, tests/unit/Support/NavigationPreferredRangeFormatTest.php, tests/unit/Support/NavigationPreferredSqlFormatTest.php
=> Cover preferred format methods of the Navigation class

resources/views/index.twig
Fixes issue # [8206](https://github.com/firefly-iii/firefly-iii/issues/8206)
- Fixed routing for category title and go_to_budget shortcut
@JC5
=> Fixed routing for category title and go_to_budget shortcut

app/Api/V1/Requests/Models/TransactionCurrency/UpdateRequest.php, app/Jobs/CreateRecurringTransactions.php, app/Support/Http/Controllers/ModelInformation.php, public/v1/js/ff/rules/create-edit.js, public/v1/js/lib/vue.js, resources/assets/js/components/transactions/AccountSelect.vue, resources/assets/js/components/transactions/Budget.vue, resources/assets/js/components/transactions/CreateTransaction.vue, resources/views/budgets/index.twig, resources/views/layout/default.twig, resources/views/layout/empty.twig, resources/views/layout/guest.twig, resources/views/layout/install.twig
Found via `codespell -q 3 -S "./resources/lang,./resources/assets/js/locales" -L hastable`
@JC5
=> Fix various typos

resources/views/transactions/mass/delete.twig
Fixes issue #8501
- Fix incorrect ID in bulk delete tx URL
@JC5
=> Fix incorrect ID in bulk delete tx URL

readme.md
=> [trivial] fix broken link in readme

resources/views/popup/list/journals.twig
noticed title when mouse hover was wrong
-
-
@JC5
=> icon title chgd from Deposit to Transfer

app/Support/Twig/General.php
This PR fixes issue #8956.
* Removes the markdown nesting level
@JC5
=> Remove nesting level for markdown

resources/assets/v1/src/components/transactions/ForeignAmountSelect.vue, resources/lang/en_US/errors.php
=> chore: fix some comments

tests/integration/Api/Autocomplete/CategoryControllerTest.php
I'm trying to improve the test coverage of the project. Will add more tests for autocomplete.
@JC5
=> add test cases for api/v1/autocomplete/CategoryController

tests/integration/Api/Autocomplete/BillControllerTest.php, tests/integration/Api/Autocomplete/BudgetControllerTest.php, tests/integration/Api/Autocomplete/CategoryControllerTest.php, tests/integration/Api/Autocomplete/CurrencyControllerTest.php, tests/integration/Api/Autocomplete/ObjectGroupControllerTest.php
- Add more test cases to autocomplete.
- Fix user group in previous test cases.
- Currently working on the rest.
@JC5
=> Autocomplete test - CurrencyControllerTest & ObjectGroupControllerTest

app/Console/Commands/Integrity/ValidatesEnvironmentVariables.php
A command to verify various environment variables.
=> Add command to validate various settings.

app/Repositories/Currency/CurrencyRepository.php, app/Repositories/Currency/CurrencyRepositoryInterface.php
=> Add missing method to repository.

app/Http/Controllers/Account/ShowController.php, app/Repositories/Account/AccountRepository.php, app/Repositories/Account/AccountRepositoryInterface.php, app/Repositories/PiggyBank/PiggyBankRepository.php, app/Support/Debug/Timer.php, app/Support/Http/Controllers/PeriodOverview.php, app/Support/Preferences.php, resources/views/list/periods.twig
=> Speed up account show

app/Providers/CurrencyServiceProvider.php, app/Providers/FireflyServiceProvider.php
=> Fix missing initialisation

app/Repositories/Bill/BillRepository.php
=> Fix #10007

app/Api/V1/Controllers/Autocomplete/AccountController.php
=> Add debug for #10005

.github/workflows/release.yml
=> Move action until after commits.

.github/workflows/release.yml, releases.md
=> Expand releases.md and add extra text to release docs.

resources/assets/v2/src/api/v1/model/account/put.js, resources/views/v2/index.blade.php
=> Small additions

resources/assets/v2/src/api/v1/model/budget/get.js, resources/assets/v2/src/pages/transactions/shared/process-attachments.js
=> add missing files

resources/assets/v2/src/api/v1/model/attachment/post.js
=> ok final one

app/Notifications/Admin/UnknownUserLoginAttempt.php, app/Notifications/Security/UserFailedLoginAttempt.php, app/Notifications/Test/OwnerTestNotificationEmail.php, app/Notifications/Test/UserTestNotificationEmail.php, app/Notifications/User/NewAccessToken.php
=> Mute notifications for demo site.

app/Support/Http/Controllers/PeriodOverview.php
=> Fix #10069

app/Http/Controllers/Export/IndexController.php, app/Support/Export/ExportDataGenerator.php
=> Add debug for #10068

app/Repositories/Category/OperationsRepository.php
This PR fixes issue #10025 (if relevant).
-
-
-
@JC5
=> Fix #10025

app/Notifications/Admin/UnknownUserLoginAttempt.php, app/Notifications/Security/UserFailedLoginAttempt.php, app/Notifications/Test/OwnerTestNotificationEmail.php, app/Notifications/Test/UserTestNotificationEmail.php, app/Notifications/User/NewAccessToken.php
=> Better mute

app/Notifications/User/NewAccessToken.php
=> Fix dumb error

app/Notifications/Security/UserFailedLoginAttempt.php, app/Notifications/Test/OwnerTestNotificationEmail.php, app/Notifications/Test/UserTestNotificationEmail.php
=> Fix lint errors

app/Repositories/Budget/AvailableBudgetRepository.php
=> Fix nullpointer.

app/Notifications/Admin/UnknownUserLoginAttempt.php, resources/lang/en_US/email.php
=> Add IP to failed login message.

app/Api/V1/Controllers/Summary/BasicController.php, app/Repositories/Budget/OperationsRepository.php
=> Possible fix for #10114

config/cer.php, database/seeders/TransactionCurrencySeeder.php
=> Add new currencies and update exchange rates.

app/Http/Controllers/Chart/BillController.php
=> Fix nullpointer in bill chart controller.

app/Services/Internal/Support/JournalServiceTrait.php, app/Validation/AccountValidator.php
=> Fix #10015

resources/views/json/piggy-banks.twig
=> Fix empty amount

resources/views/list/groups.twig, resources/views/transactions/show.twig
=> Fix #10150

config/app.php
=> Intentional code jumbling. This needs improvement in the action.

app/Support/Export/ExportDataGenerator.php
=> Fix #10068

app/Http/Middleware/TrustProxies.php
=> Fix #10162

app/Factory/PiggyBankFactory.php
=> Add some piggy bank events.

app/Http/Controllers/Budget/IndexController.php, app/Http/Controllers/Budget/ShowController.php, app/Http/Controllers/Chart/BudgetController.php, app/Repositories/Budget/OperationsRepository.php, app/Support/Http/Controllers/AugumentData.php, app/Support/Report/Summarizer/TransactionSummarizer.php, resources/views/budgets/index.twig, resources/views/budgets/show.twig
=> Fix #10114

app/Handlers/Observer/PiggyBankEventObserver.php
=> Fix nullpointer

app/Api/V1/Controllers/Summary/BasicController.php, app/Repositories/Budget/OperationsRepository.php, public/v1/js/ff/index.js
=> Fix #10180

config/firefly.php
Fixes https://github.com/firefly-iii/firefly-iii/issues/10201
- Fix Ukrainian language name in English
- Fix Ukrainian language name in the local language
@JC5
=> Fix Ukrainian language names

app/Helpers/Collector/Extensions/CollectorProperties.php, app/Helpers/Collector/GroupCollector.php, app/Http/Controllers/Account/ShowController.php, resources/lang/en_US/list.php, resources/views/list/groups.twig
=> Add running balance column.

app/Http/Controllers/Rule/EditController.php, resources/lang/en_US/firefly.php, routes/breadcrumbs.php
=> Fix #10197

app/Helpers/Collector/GroupCollector.php, resources/views/list/groups.twig
=> Fix running balance

app/Console/Commands/System/RecalculatesRunningBalance.php, app/Support/Models/AccountBalanceCalculator.php, resources/views/list/groups.twig
=> Add transfer type

app/Http/Controllers/Chart/AccountController.php
=> Fix type error.

app/Console/Commands/System/OutputsInstructions.php, app/Http/Controllers/Json/IntroController.php, app/Http/Controllers/Recurring/EditController.php, app/Services/Internal/Update/GroupCloneService.php, app/Support/CacheProperties.php
=> Replace string operators.

.ci/rector.php, .ci/rector.sh
=> Add rector

app/Api/V1/Requests/Data/Bulk/TransactionRequest.php
=> Import function.

app/Console/Commands/Upgrade/UpgradesDatabase.php, app/Http/Controllers/Controller.php
=> Fix back and forth between v1 and v2

.env.example, app/Http/Kernel.php, app/Support/JsonApi/Enrichments/AccountEnrichment.php, app/Transformers/AccountTransformer.php, package-lock.json, resources/assets/v2/src/api/v1/model/account/get.js, resources/assets/v2/src/pages/accounts/index.js, resources/views/v2/partials/dashboard/account-list.blade.php, resources/views/v2/partials/dashboard/subscriptions.blade.php
=> Fix account list and remove sanctum

app/Factory/TransactionJournalFactory.php, app/Http/Controllers/Account/IndexController.php, resources/views/javascript/variables.twig, resources/views/list/groups.twig
=> Fix #10265

app/Console/Commands/Correction/CorrectsUnevenAmount.php, app/Factory/TransactionJournalFactory.php, app/Repositories/Bill/BillRepository.php, app/Repositories/Currency/CurrencyRepository.php, app/Repositories/PiggyBank/PiggyBankRepository.php, app/Repositories/UserGroups/Currency/CurrencyRepository.php, app/Validation/AccountValidator.php, app/Validation/TransactionValidation.php
=> Fix 10265 addendum

app/Exceptions/Handler.php
=> Fix missing import.

resources/lang/en_US/firefly.php, resources/views/transactions/mass/edit.twig
=> Fix #10290

app/TransactionRules/Actions/SetDestinationAccount.php, resources/lang/en_US/rules.php
=> Fix #10302

resources/views/reports/partials/balance.twig
=> Fix #10305

app/Console/Commands/Correction/CorrectsUnevenAmount.php
=> Fix #10336

resources/assets/v1/src/components/transactions/EditTransaction.vue
=> Fix #10320

tests/integration/Support/Models/BillDateCalculatorTest.php, tests/integration/Support/NavigationCustomEndOfPeriodTest.php, tests/unit/Support/Calendar/CalculatorTest.php, tests/unit/Support/Calendar/Periodicity/IntervalTestCase.php, tests/unit/Support/NavigationAddPeriodTest.php, tests/unit/Support/NavigationEndOfPeriodTest.php, tests/unit/Support/NavigationPreferredCarbonFormatByPeriodTest.php, tests/unit/Support/NavigationPreferredCarbonFormatTest.php, tests/unit/Support/NavigationPreferredEndOfPeriodTest.php, tests/unit/Support/NavigationPreferredRangeFormatTest.php, tests/unit/Support/NavigationPreferredSqlFormatTest.php, tests/unit/Support/NavigationStartOfPeriodTest.php, tests/unit/Support/Search/QueryParser/AbstractQueryParserInterfaceParseQueryTester.php
=> Fix phpunit tests

app/Api/V1/Controllers/Models/TransactionCurrency/ListController.php
Set the start and end parameters on the enricher
=> Fix #11010 currency account list range
