- database/migrations/2014_12_13_190730_changes_for_v321.php
- database/migrations/2014_12_24_191544_changes_for_v322.php
Several fixes in the migrations files that generated errors when reversing migrations (For example on a migrate:refresh)
> Fix migrations

- resources/twig/auth/login.twig
- resources/twig/auth/password.twig
- resources/twig/auth/register.twig
Improvement of previous pull request #85. This update uses the URL.to method for renedering the URL's on the login screen.
> use relative path in login screen improved

- config/twigbridge.php
The upstream project has changed the class to Str.
> String is a reserved class name in php 7.

- app/Support/Binder/Date.php
- resources/lang/en_US/firefly.php
- resources/views/reports/index.twig
As per the discussion on issue #131 I have added a current fiscal year quicklink report.
The reason for instantiating the helper at the beginning of the static function routeBinder
is I am hoping that the object will only be created once. But I am not very familiar with the workings of static functions so I could be wrong.
> Quicklink fiscal year report feature. As per github issue #131.

- app/Models/RuleTrigger.php
- app/Rules/Triggers/AmountExactly.php
- app/Rules/Triggers/AmountLess.php
- app/Rules/Triggers/AmountMore.php
- app/Rules/Triggers/DescriptionContains.php
- app/Rules/Triggers/DescriptionEnds.php
- app/Rules/Triggers/DescriptionIs.php
- app/Rules/Triggers/DescriptionStarts.php
- app/Rules/Triggers/FromAccountContains.php
- app/Rules/Triggers/FromAccountEnds.php
- app/Rules/Triggers/FromAccountIs.php
- app/Rules/Triggers/FromAccountStarts.php
- app/Rules/Triggers/ToAccountContains.php
- app/Rules/Triggers/ToAccountEnds.php
- app/Rules/Triggers/ToAccountIs.php
- app/Rules/Triggers/ToAccountStarts.php
- app/Rules/Triggers/TransactionType.php
- app/Rules/Triggers/TriggerInterface.php
- app/Rules/Triggers/UserAction.php
For proper implementation of a feature to run rules on existing transactions, a check was needed to see if a trigger would match any transaction. In that case, the user should be warned. To perform this check, I've extended the existing trigger objects to do type-specific checks.
> Check for triggers that match anything

- public/js/reports/default/month.js
- public/js/reports/default/reports.js
The line charts on report pages weren't loading for me, turns out the graphs were trying to load the data from an absolute instead of a relative URL.
> Fix use of absolute URLs for linecharts for the report pages.

- database/migrations/2016_09_12_121359_fix_nullables.php
This should fix #310 by adding a migration that updates the nullable values. Users would have to perform an `php artisan migrate` to apply the change.
> add migration that correctly sets nullable for description fields on rules and rule_groups

- app/Helpers/Report/ReportHelper.php
- app/Import/ImportStorage.php
- app/Repositories/Account/AccountRepository.php
- app/Repositories/Budget/BudgetRepository.php
- app/Repositories/Category/CategoryRepository.php
This pull request introduces PostgreSQL compatibility, and potentially compatibility for other databases as well.
More specifically, the use of XOR has been replaced with a construct native to Eloquent.
This is intended to fix #346 and might also fix #279.
@JC5 I realize there is a lot of code duplication but I was unsure of where to refactor the duplicate code to. Feel free to point me in the right direction or do it yourself.
> PostgreSQL compatibility

- composer.json
The intl extension is used for NumberFormatter at the very least. Explicitly requiring it in composer.json would make troubleshooting the install much simpler. I had to do a surprising amount of googling before finding out numfmt_create was in the intl extension.
Having done this I have a perfectly-working firefly install in a development environment though 😁
> Require PHP intl extension

- Dockerfile
- docker/apache-firefly.conf
Ok, so this one is mostly based off #358. With a few difference which might actually make it easier.
First of all, this image is based of php:7-apache instead of ubuntu directly. Second of all, no configuration (.env) is stored in the image itself. To run this, use a run command that looks something like this
```docker run --name firefly-iii --link firefly-iii-db:db -v /data/firefly-iii/env:/var/www/firefly-iii/.env:ro firefly-iii```
This does assume there is a database with data already present, if not you'll have to run something like this first
```docker run --rm -it --link firefly-iii-db:db -v /data/firefly-iii/env:/var/www/firefly-iii/.env:ro firefly-iii php artisan migrate --seed --env=production```
> Added dockerfile

- public/js/ff/charts.defaults.js
The graphs created using Chart.js are using smooth curves that look pleasant, but overshoot or undershoot the values between data points.
We can set `cubicInterpolationMode` to `monotone` in order to avoid this behavior.
Example of what was happening:
> Fix smooth curves around data points in graphs

- .gitignore
- docker-compose.override.yml
- docker-compose.prod.yml
- docker-compose.yml
As mentioned in #561 the current docker-compose setup does not persist data which means that all data will be gone when the Docker containers are stopped. This PR resolves that by creating a separate docker-compose file that is suitable for production use. It uses a Docker volume to store data for the app.
After starting (using `docker-compose -f docker-compose.prod.yml up -d`), you still need to seed the database (can't be done automatically for production AFAIK) by running `docker exec -ti firefly-iii php artisan migrate:refresh --seed`. After this, you should be ready to go and your data will be available after restarts.
> Use Docker volumes created by docker-compose to persist data

- app/Http/Requests/TagFormRequest.php
The `date` function takes the fieldname where a date is stored, not the literal date.
> Fix saving a tag’s date

- resources/views/transactions/single/create.twig
Fixes #605. By explicitly setting the selected piggybank to the 0-piggy, new transactions will not inadvertently get coupled to a piggybank if the piggy’s name starts with characters that get sorted before `(` (such as `!` or `’`).
> Set default piggy for new transaction

- resources/views/partials/favicons.twig
If you access with absolute path, favicon don't appear on site and manifest.json isn't load on android Chrome. Get 404 error
> Changed to get relative path and not absolute path

- Dockerfile
fwd #663
> Hello. This tiny change makes possible to use firefly on pgsql driver in docker container.
> Add pgsql dependencies to Dockerfile

- resources/lang/en_US/firefly.php
There was a small typo/error on the create revenue account page.
> Fix en_US translation: no_accounts_imperative_revenue.

- public/js/ff/charts.js
* Do not fill the area below the lines
* Provide border color
* Decrease transparency of border
> Make charts easier to read

- app/Support/Amount.php
When currency symbol follows amount, space should be between amount and symbol, not before amount.
Just like PHP does it:
```
> php -r 'setlocale(LC_ALL, "pl_PL.utf8"); echo money_format("%n", 12345.67);'
12.345,67 zł
> php -r 'setlocale(LC_ALL, "pl_PL.utf8"); print_r(localeconv());'
Array
(
[decimal_point] => ,
[thousands_sep] =>
[int_curr_symbol] => PLN
[currency_symbol] => zł
[mon_decimal_point] => ,
[mon_thousands_sep] => .
[positive_sign] =>
[negative_sign] => -
[int_frac_digits] => 2
[frac_digits] => 2
[p_cs_precedes] => 0
[p_sep_by_space] => 1
[n_cs_precedes] => 0
[n_sep_by_space] => 1
[p_sign_posn] => 1
[n_sign_posn] => 1
[grouping] => Array
(
)
[mon_grouping] => Array
(
[0] => 3
[1] => 3
)
)
```
> Fix formatting when currency symbol is separated and follows amount

- .dockerignore
- .gitignore
- Dockerfile
- By using the current (.) working directory, we can get the latest changes in the Docker image.
If the building of Docker images is automated, it will automatically pick up the checked out version.
- Rearrange some Docker layers things that don't invalidate that much.
> Docker: Use working directory instead of hardcoded dist version

- Dockerfile
While Apache configuration file will still have to be customize, this makes one file less to modify when running Docker containers
> Enable mod_ssl in docker container

- app/Import/Mapper/OpposingAccounts.php
When mapping Opposing Accounts the select input's values are incorrect and do not match account ids.
- 
- 
- 
@JC5
> Fix issue with accounts in select map not matching

- public/js/ff/charts.js
As it stands, I happened to notice that the charts in Firefly-III don't render on IE.  
Turns out it seems like IE has no support for arrow function expression (and thus throws a syntax error).
Fortunately, the fix seems to be quite a simple one.    Once I changed the particular `=>` instance at L91, charts.js, the charts seem to be back again on IE.    So basically this patch's to make IE happy.
Tested it out on my machine, 4.6.13 with this patch, and both Chrome and IE 11 successfully render the charts.
> Fix charts in Internet Explorer

- public/js/ff/guest.js
(Sorry if it's another IE (quirk) fix) 
(This [SO question](https://stackoverflow.com/questions/628235/tab-order-issue-in-ie-with-initial-javascript-select-of-field-in-form) actually identifies succinctly the issue that, so happens, I've come across and I gratefully adopt a proposed fix from one of its answers)
_tl; dr: ~~probably~~ apparently an IE bug, but hopefully a simple (and not very intrusive to other browsers) fix to revive some convenience to IE users_
(I think it probably occurs only in IE)
1. Type in the address bar (say `demo.firefly-iii.org`) to navigate to the login page.
The site will load.  The js kicks in and selects the first input (ie `Email address`) field.
2. With the blinking text cursor in the textbox, type in something, like`demo@firefly`.  Press Tab.
3.  Instead …
> Workaround IE tab order issue on js initial select

- resources/views/partials/menu-sidebar.twig
I noticed a minor thing which was bothering me. The Icons in the sidebar weren't align correctly (the fa-repeat icon). This change should fix this.
I hope it's okay, that i didn't ask you before :smile: 
- Add "fa-fw" class to "fa-repeat" icon
@JC5
> Fix alignment of sidebar-icons

- .sandstorm/Vagrantfile
- .sandstorm/global-setup.sh
- .sandstorm/setup.sh
Note that vagrant-spk currently uses Stretch, but that'd likely require more changes and testing on your other build files. I was unable to fully test the Firefly III build because I was doing this on a Windows box, and vagrant-spk + Windows + symbolic links = sadness.
- Updated box to official Jessie 64
- Made one of your install commands accept without prompt in setup.sh
- Ensured Vagrantfile works on more versions of Vagrant
@JC5
> Update Sandstorm build instructions

- .gitignore
- app/Repositories/User/UserRepository.php
Fixes #1589
- Used the right object to attach as role. Instead of String now the real Role object is used
@JC5
> BUGFIX: Initial user not set as owner

- Dockerfile
- Readded missing ENV variables for OpenSSL and CURL versions
- Moved add/copy of firefly down to end of Dockerfile to make better use of Docker image layer caching
> fixed missing ENV variables

- app/Http/Controllers/Transaction/SingleController.php
- resources/views/partials/flashes.twig
Adds option for messages to contain a link (issue #1623), and makes single transactions use that option
@JC5
> Can have link in success message to the transaction it refers to

- app/Http/Middleware/SecureHeaders.php
Error in console:
Refused to load the image 'data:image/png;base64,...' because it violates the following Content Security Policy directive: "img-src 'self'".
Relevant stackoverflow fix:
https://stackoverflow.com/questions/18447970/content-security-policy-data-not-working-for-base64-images-in-chrome-28
- Adding data scheme to CSP config of image sources
@JC5
> 2FA QR doesn't show up due to CSP error

- .github/ISSUE_TEMPLATE/Bug_report.md
Helps to understand how the bug violates what the user expect to happen in normal scenario.
- Github bug report template
@JC5
> Add expected behavior to bug report template

- composer.json
There are situations where php executable is not in path or is not called `php` in those cases `composer update` and `composer install` will break or might use php version which might not be the same as the one running the composer process.
One of the examples can be that on your system you have at least two versions of PHP. One available as `php` the other as `php.7.1` and so on.
If you were to run `php7.1 /path/to/composer.phar install` in the project directory, the composer will be executed by `php7.1` but the artisan scripts will be run under `php` executable and most likely will fail.
Defining scripts in `composer.json` which reference `php` executable using `@php` token avoids this issue.
/ref https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts
/ref …
> Make sure PHP executable is being resolved by composer

- app/Support/Import/JobConfiguration/Bunq/ChooseAccountsHandler.php
When using the bunq import and unchecking "apply rules" gave an error. Same as #1538
based on develop branch this time ;)
@JC5
> Fix bunq import "Undefined index: apply_rules"

- public/js/ff/transactions/list.js
Maybe bug (not verified) when mass editing/deleting transactions when Firefly installed in directory.
Couldn't find similar coding pattern in other js files from a quick look (referencing base in uri),
what should be the recommended pattern in this case?
- remove first slash in mass transaction changes
- 
- 
@JC5
> remove first slash in mass transaction changes

- .locales
- app.json
Starting from heroku 16 stack the language packs are not included by default: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-locale
Fixes [#8](https://github.com/firefly-iii/help/issues/8)
- Fixed locales lang error on Heroku build platform
@JC5
> Fixed locales lang error on Heroku build platform

- app/Repositories/Bill/BillRepository.php
- resources/views/list/bills.twig
Fixes #1771 (if relevant)
- Adds the link to the transaction from dates in the bill
- Does not implement said changes in the Vue component (as it is unused currently)
@JC5
> Add links to transaction from dates in bill, closes #1771

- resources/views/bills/show.twig
- bills: match attachment route with the icon
@JC5
> bills: match attachment route with the icon

- app/Http/Middleware/SecureHeaders.php
- Fixed CSP value that block Google Fonts and fonts loaded by (local) base64 code
- Added CSP directive to load manifest file ([site.webmanifest](https://github.com/firefly-iii/firefly-iii/tree/master/public/site.webmanifest))
@JC5
> Fixed missing CSP directive and value

- Dockerfile
- Added libmemcached-dev package to apt-install
- Added opcache to php-extensions to install
- Added pecl installation of memcached-3.1.3 (used explicit version as recommended on https://hub.docker.com/_/php/ )
Memcached can be used by providing the following environment variables:
MEMCACHED_PERSISTENT_ID=[random-string-unique-for-installation]
MEMCACHED_HOST=[adres-of-memcached-server>]
CACHE_DRIVER=memcached
@JC5
> Added memcached support and zend opcache

- resources/views/v1/profile/delete-account.twig
Steps to reproduce:
- Go to Options, Profile, Delete account
- Enter password
- Click "DELETE your account"
- Confirmation dialog appears: "Are you sure? You cannot undo this." (OK/Cancel)
- Click **Cancel**
Expected behavior:
- Account is not deleted
What happens instead:
- Account is deleted
- Do not delete account if user cancels confirmation dialog
@JC5
> Fix delete-account confirmation

- resources/views/v1/layout/default.twig
- resources/views/v1/layout/empty.twig
- resources/views/v1/layout/guest.twig
- resources/views/v1/layout/install.twig
Fixes:
url bar on home screen web app visible on ios and not on android.
Tested on ios. Want more space on screen when using firefly III on mobile as homescreen app.
- added 
```html
<meta name="apple-mobile-web-app-capable" content="yes">
``` 
@JC5
> missing meta tag for ios

- config/ldap_auth.php
- database/migrations/2019_03_11_223700_fixldap.php
This commit fixes parameters broken in the latest version of `adldap2`.
Specifically:
* `adldap` auth parameters have changed in the latest version.
* "usernames" has become `identities` and `discover` has changed to
`discover_users_by`, `auth` has changed to `bind_users_by`
* Add the missing objectguid field to the users table for adldap2.
* This is added as a nullable (optional) field at the moment to support
tracking LDAP users as adldap2 wants to.
Fixes issue #1933 (completely).
- Database migration for `objectguid`
- Change the paths in `config/ldap_auth.php` to match up `adldap2`
With these changes I was able to get authentication with FreeIPA working correctly versus current master.
@JC5
> Fix LDAP auth configuration paths.

- .deploy/docker/entrypoint.sh
- .deploy/docker/wait-for-it.sh
- Dockerfile
- Dockerfile.amd64
- Dockerfile.arm
(Sorry @JC5, accidentally added this pull request to the master branch just now. Hope you won't mind.)
Follow-up of #2122.
- Added [wait-for-it.sh](https://github.com/vishnubob/wait-for-it/)
- Used `wait-for-it.sh` to make sure DB is already up before running DB-dependent artisan commands
- Moved lengthy `docker-php-ext-install`s to top of `Dockerfile*`. Drastically improved build time while testing changes in `FIREFLY_PATH`
@JC5
> Docker's entrypoint.sh: wait for DB before running DB-dependent artisan commands

- app/Import/Specifics/Belfius.php
- config/csv.php
- resources/lang/en_US/import.php
- tests/Unit/Import/Specifics/BelfiusTest.php
This pull request adds a CSV file fix option for Belfius Bank (Belgium). 
Belfius CSV files have, among other columns, a column containing the transaction description ("mededeling") and a "transaction" column, containing a short summary of the transaction (which also includes, but is not limited to, the transaction description or "mededeling").
For outgoing recurring transactions, the "mededeling" column contains the same short summary of the transaction as the "transaction" column.
This causes problems when the outgoing recurring transaction is a recurring transaction to another account that gets imported as well. The transaction descriptions can't be matched since the "mededeling" column for the outgoing transaction contains more than just the transaction description, unlike the …
> CSV file fix for Belfius

- app/Services/Currency/RatesApiIOv1.php
- Correct the endpoint for ratesapi. The current one returns 500, the new one works correctly.
@JC5
> Correct ratesapi URL

- app/Import/Specifics/IngBelgium.php
- config/csv.php
- resources/lang/en_US/import.php
- tests/Unit/Import/Specifics/IngBelgiumTest.php
This pull request adds a CSV file fix option for ING Bank (Belgium).
ING Belgium stores the opposing account name, IBAN and the transaction's description together in 1 column in their CSV exports instead of multiple columns that can be mapped to transaction properties in Firefly.
This extracts that information into separate columns.
> CSV file fix for ING Belgium

- app/Repositories/Budget/BudgetRepository.php
- Fixed typo in BudgetRepository which could trigger an SQL error during a GET `/api/v1/available_budgets` with the `end` parameter set. 
@JC5
> Fix typo in BudgetRepository (emd_date)

- app/Api/V1/Requests/CurrencyRequest.php
Fixes issue #2441 
- Made the character limit for currencies consistent in the API with the GUI 
I swear I looked into the code to see if this was a fix I could do. I should look harder before filling an issue next time :sweat_smile:
However I noticed the rules for `decimal_places`, `enabled` and `default` are not there. Is this intentional (I don't know, some kind of inheritance maybe)?
@JC5
> Fix consistency in symbol character limit

- app/Http/Requests/Request.php
Typo I introduced in f8cb5ca21c9a38666134966c59626c82be4a4eaf
Fixes potential error: `Symfony\Component\Debug\Exception\FatalThrowableError: Return value of FireflyIII\Http\Requests\Request::nullableNlString() must be of the type string, null returned`
- Fixed definition of Request->nullableNlString
@JC5
> Fixed definition of Request->nullableNlString

- public/v1/js/ff/rules/create-edit.js
-    change the endpoint for creating/editing rules to the correct one
This issue affects also current stable release.
@JC5
This should be a legitimate pull.
Also a warning: all "convert" select list suffers from the same problem, but i can't find a way to create an autocomplete for accounts filtered by type.
`createAutoComplete(inputResult, 'json/accounts?type=revenue');` does not works.
A temporary workaround should be `createAutoComplete(inputResult, 'json/accounts');`  but does not filter the account type.
> Fix account endpoint in create-edit.js

- app/Import/Converter/BankDebitCredit.php
Example CSV export from Community America, a Credit Union in the US:
``` csv
12/11/19,Five Guys,Sale FIVE GUYS,14.51,Debit,Food & Dining,Fast Food,CC1,,,false
12/11/19,Interest Income,Interest Earned,0.01,Credit,Income,Interest Income,Regular Savings,,Interest Earned,false
```
"Debit" is used in the type column instead of negative values in the amount column.
Fixes issue # (if relevant): None created
- Adds "Debit" to list of generic debit/credit terms
@JC5
> Add Debit to Generic Debit Credit indicator converter

- app/Support/Import/Routine/File/ImportableConverter.php
PHP allowed array accesses with curly braces but [deprecated the feature](https://wiki.php.net/rfc/deprecate_curly_braces_array_access) with 7.4. With this change the CSV import will work on 7.4 without any errors or warnings. The change does not affect other versions.
Side node: everything else I tested seems to work well with 7.4.1.
> Change a newly-deprecated array access

- app/Api/V1/Requests/AttachmentStoreRequest.php
- app/Api/V1/Requests/AttachmentUpdateRequest.php
Currently when creating/updating an Attachment, we need to use the fields `model` and `model_id` to specify the object the attachment refers to. However to read the same values back from the API the names are `attachable_type` and `attachble_id`.
This PR fixes this inconsistency. I choose to roll with `attachable` rather than `model` because it makes more sense and (probably) requires the least changes, even though it creates an inconsistency with the DB table.
> API: Unified attachment_* and model_* for Attachments

- .env.example
Fixes issue #3091 
Move comment about quotes in redis db index to own line. The comment in the variable caused redis to use `"0" #always use quotes` as redis db index instead of just `"0"`.
> Move redis comment to different line

- app/Support/Search/Search.php
The regex being used to detect search modifiers was only restricted to characters without the Unicode property Other, which is most characters, including spaces. That meant that almost anything following a modifier got treated as part of it, breaking, among other things, combining modifiers. This version will include anything but a space, unless the value is quoted, in which case it'll accept anything.
> Fix search modifiers claiming the whole query

- resources/views/v1/list/groups.twig
- Bottom border on transactions list header did not continue the whole way, a couple of column headers were missing
- action buttons were aligned differently for single and split transactions.
**Before:**
**After:**
@JC5 didn't discuss first hope that's ok.
> add 2 <th> to fix header row border, fix alignment on action btn

- app/Import/Specifics/IngDescription.php
Fixes issue #2642
- Added `DV` transaction type (Divers)
- Correctly remove `Naam` and it's value from `Mededelingen` collumn
- Remove the word `Omschrijving` from `Mededelingen` collumn
- Fix copy of bank account number and name when transaction is an transfer from/to saving account.
- Move `Valutadatum` from `Mededelingen` collumn to an own collumn. Right now the collumn itself has no name.
Todo:
- Add an name for the newly created collumn. I have done this hardcoded by adding this line:
``` php
array_push($headers, "Valutadatum"); // New row for "Valutadatum" (only for IngDescription.php specific import)
```
To here (between `$headers` and `// get example rows:` (line 253))
https://github.com/firefly-iii/firefly-iii/blob/af503597e62108cd7fedaa8ef89c80d161cb …
> Better CSV import for ING (NL)

- changelog.md
- add missing date based on releases page
- add missing final new line by accident
@JC5
> Add missing date based on releases page

- app/Repositories/Account/AccountRepository.php
- resources/lang/en_US/firefly.php
Fixes issue #3335 
- Add optional `$currencyId` argument to `AccountFactory::findOrCreate` method which passes currency_id to `AccountFactory::create` method
- Get currency_id of current account in `AccountRepository::getReconciliation` method if reconciliation is not created yet
- Pass `currencyId` to `AccountFactory::findOrCreate` method if available
@JC5
> WIP: Fix #3335 Reconciliation account currency is wrong when base account has non-default currency

- app/Http/Controllers/Transaction/ConvertController.php
- app/Support/Form/AccountForm.php
- app/Support/Steam.php
Fixes issue #3597
Root cause:
- If there's a lot of accounts to calculate balances for, then recurring transactions create page
doesn't load. Partly because it has to calculate a lot of balances, but partly because the cache
isn't being used at all because date is `new Cobra` rather than say, end of month.
- Change Steam balance calculator to always default cache using end of month. Since cache is
'invalidated' upon any edit, there's no reason to use current datetime anywhere its not explicitly
required by user flow.
- Don't calculate balances for revenue / expense accounts since those are unbounded (similar to
auto complete form).
Test Plan:
1. Opened `/recurring/create` and it loaded fine (albeit slow).
2. Reloaded and verified zero instances of `Steam` in …
> Fix recurring transactions create and fix cache access

- resources/lang/en_US/firefly.php
- resources/views/v1/preferences/index.twig
Following d774b4e, I suggest to remove Docker mention since this block is displayed only when not running Docker.
@JC5
Not sure what's your politic about unused strings, let me know if you want me to remove it (same for my other PR).
> Remove mention of Docker when not running Docker

- app/Support/Steam.php
- resources/lang/en_US/firefly.php
- resources/views/v1/preferences/index.twig
> UTF8 locale support for Windows

- app/Http/Controllers/PiggyBank/IndexController.php
The recent implementation of groups to piggy banks does not handle correctly the case where no piggy banks are assigned to the default group.
When other piggy banks are assigned to a group, it is not visible. But when no piggy banks exist at all, the "Let's create a piggy bank!" frame is not displayed.
@JC5
> Fix "Let's create a piggy bank!" not being displayed anymore

- resources/views/v1/budgets/index.twig
Before:
After:
Minor UX improvement for a new user IMO. Thought also about hiding the "Total available budget" frame, but I'll leave it up to you.
@JC5
> Hide budgets list when it is empty

- app/Scopes/LdapFilterScope.php
- config/ldap_auth.php
Fixes issue #3723
- Add ldap_auth.custom filter option
- Add ADLDAP_AUTH_FILTER env reference
- Create LdapFilterScope to apply the filter (if one exists) to LDAP queries
@JC5
> Add config option to specify custom LDAP filter

- public/v1/js/ff/transactions/convert.js
- public/v1/js/ff/transactions/mass/edit.js
Query string with two ?, broke some autocompletes. Probably an unlucky search&replace while migrating to the new API.
Btw, wouldn't be cleaner to use "expense" and "revenue" instead of "Expense account" and "Revenue account", since it is supported by the API?
> Wrong query params in autocomplete

- public/manifest.webmanifest
Hi,
Re #3821 , It appears `start_url` is a mandatory field. See Chrome DevTools output:
I'm serving Firefly over http, so you can ignore the first warning. The last warning is because Firefly is not offline-ready, i.e. does not use a service worker.
Thanks!
> Add start_url to manifest file

- database/seeds/TransactionCurrencySeeder.php
Hi. This fix for little mistake in ruble currency name as  ` `
- Change currency name from `Russian ruble ` to `Russian ruble`
@JC5
> Fix space ruble currency name

- app/Support/Authentication/RemoteUserGuard.php
493d399 - Fix a typo
be421d0 - Fix an issue I had using "remote_user_guard", the REMOTE_USER header was not forwarded to the app -> Exception "The guard header was unexpectedly empty. See the logs."
I know my fix is not perfect : if someone edit AUTHENTICATION_GUARD_HEADER to something different .. then it won't work anymore. Maybe a note should be added, or do you have another idea to forward that header ?
@JC5
> Forward REMOTE_USER (remote_user_guard auth mode)

- app/Api/V1/Controllers/Search/TransactionController.php
This change updates the transaction search api controller to use user preferences when setting a query limit as the previous config has been removed. Without this change, the search api always returns 0 entries.
@JC5
> Updated Transaction Search API to set limit from user preferences

- app/Support/Authentication/RemoteUserGuard.php
Fixes issue #4060
- Do not fail with 500 on missing `AUTHENTICATION_GUARD_EMAIL` configuration
@JC5
> Fix remote guard email header

- app/Http/Controllers/Json/BoxController.php
If no available budget is set, the budget box displays the total spent amount. The 'per day' amount is broken though, it's initialized to -1 but never set.
Tested with past and future periods as well.
@JC5
On a side note, I wonder if the negative amount is intended? If it's spent it's obviously negative. Same goes for 'Bills to pay' box.
> Fix 'spent per day' budget box

- app/Http/Controllers/Bill/IndexController.php
- Interface bills overview did not show expected monthy costs correctly (skips were ignored)
- amountPerPeriod() has been adapted to include skips
@JC5
> Fixed amountPerPeriod not respecting bill skips

- app/Jobs/CreateAutoBudgetLimits.php
Fixes issue (none)
When trying to fin the reason why new budget limits were not created by the cronjob it appeared that sqlite does not return php integers for integer types. Instead it returns a string for everything.
This PR resolves this by casting the auto_budget_type to int
@JC5
> BUGFIX: sqlite does not return int types

- app/Http/Controllers/HealthcheckController.php
- routes/web.php
- This PR adds a /health endpoint which does nothing more than returning plaintext OK response. It is useful for service discovery tools (consul/kubernetes etc.), to quickly say, that service is alive and running. 
@JC5
> healthcheck endpoint

- config/auth.php
> Drop default case. OpenLDAP is already the default (see #5279)

- app/Http/Controllers/Budget/EditController.php
The auto-budget pre-filled value is empty when the set amount is above 1000 (view /budgets/edit/X).
The root cause was the function 'number_format' returning a string that
cannot be casted to a float when the amount is above 1000, because of the
thousands separator.
Introduced by commit b2eeeed0af in 5.6.5.
@JC5
> Bugfix: Empty pre-filled value in auto-budgets

- .github/contributing.md
- readme.md
- I have updated the readme.md to directly point the contributing documentation on the project website instead a GitHub landing
- Removed .github/contributing.md which is unnecessary at this point
(#5653 was on main branch)
@JC5
> direct link to contributing docs in readme.md

- .github/workflows/lock.yml
- .github/workflows/stale.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- config/firefly.php
This add the ability to disable mime check on file upload.
(In my case I want to upload eml mail file and json metadata)
- Add a new env variable `DISABLE_UPLOAD_MIME_CHECK` to control the new behavior
- Edited `AttachmentHelper.php` to create that new behavior
@JC5
> feat: add the ability to disable mime check on attachement upload

- app/Repositories/PiggyBank/PiggyBankRepository.php
Fixes issue #6254
- Factor in PiggyBank->startdate into getSuggestedMonthlyAmount to enable time bound calculations
@JC5
> Use Piggy Bank's start date in suggested monthly calc

- config/database.php
Redis username needed for both 'default' and 'cache' databases.
I got this error message after updating firefly III to 5.7.11 :
```
php ./artisan cache:clear
Predis\Connection\ConnectionException 
`AUTH` failed: WRONGPASS invalid username-password pair or user is disabled. [unix:/var/lib/redis/redis.sock]
at vendor/predis/predis/src/Connection/AbstractConnection.php:132
128▕      */
129▕     protected function onConnectionError($message, $code = 0)
130▕     {
131▕         CommunicationException::handle(
➜ 132▕             new ConnectionException($this, "$message [{$this->getParameters()}]", $code)
133▕         );
134▕     }
135▕ 
136▕     /**
+25 vendor frames 
26  artisan:37
Illuminate\Foundation\Console\Kernel::handle()
```
> Redis username needed for both databases

- config/bulk.php
- Ensures that the validation rules for bulk endpoint match what the bulk TransactionController expects: `source_account_id` and `destination_account_id` ==> `account_id`
---
Hey @JC5, I just started using Firefly III, and noticed that the `/api/v1/data/bulk/transactions` endpoint did not work as expected. With my limited PHP foo I was able to pin-point it to a mismatch on argument names, as I was getting the error
> JSON contains an invalid key for the \"where\"-clause
despite using the right keys. Changing the validation rules accordingly fixes the problem. I validated this PR in my local instance, where I can now change transactions in bulk as expected. 👌 
Thanks for creating Firefly III in the first place, I really enjoy getting to know it!
Cheers!
> Make bulk rules clauses match bulk TransactionController params

- resources/views/profile/code.twig
The QR code (and manual code) should not be recoverable after the initial setup. This would allow an unauthorized person to access an account without leaving a trace (like showing that a backup code was used, given that person has the account password).
Even if very low, having that information visible could be a problem.
---
- Add CSS classes to hide sensitive information when printing the 2FA setup page
- Hide instructions on how to use the QR code
- Remove dead code
Previews:
@JC5
> Hide sensitive information in 2FA setup page when printing

- app/Validation/Api/Data/Bulk/ValidatesBulkTransactionQuery.php
- Before validating the currency IDs for source/destination accounts in bulk transaction update action, verify if the result of `AccountRepositoryInterface::getAccountCurrency` is not null
---
Hello,
I'm playing around the Firefly III API willing to clean up my transactions and duplicated expenses accounts after import. With bulk transaction update endpoint I wanted to move all transactions from duplicated account into one particular. However, I was getting an error:
```
[2023-01-14 14:50:38] local.ERROR: Attempt to read property "id" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /var/www/html/app/Validation/Api/Data/Bulk/ValidatesBulkTransactionQuery.php:71)
```
The validator mentioned in stack …
> Do not validate currency if account has no currency configured

- app/Http/Middleware/AcceptHeaders.php
- Fix upload attachment via API
The `AcceptHeaders` middleware introduced in v6.0 limits the allowed content type of an API call to `application/x-www-form-urlencoded`, `application/json` and `application/vnd.api+json`. A 415 error will be raised for other content types. `POST ​/v1​/attachments​/{id}​/upload` [requires](https://github.com/firefly-iii/api-docs/blob/ed398f903aa12e03eff702455fad7674f1f2e891/firefly-iii-2.0.0-v1.yaml#L4640-L4645) `application/octet-stream`, thus is broken with this middleware.
This PR adds `application/octet-stream` to the allowed list.
@JC5
> Fix upload attachment via API

- app/TransactionRules/Actions/ConvertToDeposit.php
- a minor fix on the ConvertToDeposit, a missing parameter in the where condition.
When the rules triggers, I'm getting this error:
Internal Firefly III Exception:
SQLSTATE[22007]:
Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '=' (Connection: mysql,
SQL: update `transactions` set `account_id` = 254 where `transaction_journal_id` = = and `amount` < 0
)
I hope this fix it, I've also checked others ConvertToX rules, but they look good to me.
@JC5
> Rule ConvertToDeposit: fix missing parameter

- resources/views/partials/menu-sidebar.twig
In 6.0.23 version where the URLs were broken caused by @JC5 :)
I noticed that the bills section in menu sidebar had also the bug, so I fixed removing other parameters.
@JC5
> URL is broken in bills section from menu sidebar

- resources/assets/js/components/webhooks/Index.vue
On the webhooks index page there are two "create new webhook" buttons. One above and one below the table listing the webhooks. When there are no webhooks both buttons are right next to each other which looks kind of like a mistake.
- Hide duplicated webhook create button when there are no webhooks
Empty table before:
Empty table after:
<details>
<summary>With existing webhooks (before and after):</summary>
</details>
@JC5
> Hide duplicated webhook create button

- .github/workflows/sonarcloud.yml
- app/Console/Commands/System/CreateDatabase.php
- composer.json
- phpunit.xml
- tests/integration/Api/Autocomplete/AccountControllerTest.php
- tests/integration/Support/NavigationCustomEndOfPeriodTest.php
- tests/unit/Support/NavigationEndOfPeriodTest.php
The custom frequency requires a timezone configuration, forcing it to run in the integration test scope.
Running the integration tests requires a database connection in the build process. It enables other case tests.
The API Tests cause interference in other tests, requiring isolating them.
-
-
-
@JC5
> Cover endOfPeriod method of the Navigation class

- .env.example
- Update outdated documentation URLs in .env.example
@JC5
> Update outdated documentation URLs in .env.example

- resources/views/budgets/index.twig
Fixes issue #8732  (if relevant)
- Fix `Division error by zero` in budget views
-
-
In that issue (#8732), you only fix "Left to Spend" box in dashboard (commit: https://github.com/firefly-iii/firefly-iii/commit/3268019d0cf67b7c726b574d89a54c81c0c2e417). But the budget views itself hasn't been fixed. In this PR i have provide fix for that, i implemented your code from commit https://github.com/firefly-iii/firefly-iii/commit/3268019d0cf67b7c726b574d89a54c81c0c2e417 into budget views. If there is any mistake, i apologies, i'm not good with PHP language. I have tested this locally in my server and it works without error
@JC5
> Fix `Division error by zero` in budget views

- app/Services/Internal/Update/GroupCloneService.php
Fixes issue # None
- Set date to now when cloning journal
Commit https://github.com/firefly-iii/firefly-iii/commit/c979cfcd89457188976b2a9df04b22c02fa26e88 change the date from `Carbon::now()` to `today(config('app.timezone'))` when cloning journal
I believe when we clone a transaction, we hope the date to be now, not the start of today.
@JC5
> Set date to now when cloning journal

- resources/views/accounts/reconcile/transactions.twig
in reconcile view, I noticed the title when hovering mouse over the Transfer Icon, was displaying "Deposit"
-
-
@JC5
> icon title chgd from Deposit to Transfer

- resources/views/accounts/reconcile/transactions.twig
in workflow of reconciling account, sometimes a record needs to be deleted (i.e. in event of a duplicated transaction from an import or error) and this change adds an icon to the delete route
-
-
-
@JC5
> add icon for delete action

- app/Support/Navigation.php
- tests/unit/Support/NavigationEndOfPeriodTest.php
```
if ('MTD' === $repeatFreq) {
return $end->startOfMonth()->startOfDay();
}
```
Updated this block to return the correct MTD (start of month) in Navigation.php.
@JC5
> fix Navigation.php MTD logic to make tests pass.

- tests/integration/Api/Autocomplete/BillControllerTest.php
- tests/integration/Api/Autocomplete/BudgetControllerTest.php
Add test cases for `Api\V1\Controllers\Autocomplete\BillController.php`
---
Add test cases for `Api\V1\Controllers\Autocomplete\BudgetController.php`
They are kind of similar, so I felt no need for 2 separate pull requests.
@JC5
> Add  test cases for Api\V1\Controllers\Autocomplete\BillController & BudgetController

- tests/integration/Api/About/AboutControllerTest.php
- tests/integration/TestCase.php
Changes in this pull 
- Added simple tests for about endpoints in v1 api.
- I've added a method for creating an authenticated user in tests/integration/TestCase.php, as I think this will most likely be used in some other tests, by me and @tasnim0tantawi.
@JC5
> Add about test

- resources/assets/v1/src/components/webhooks/Index.vue
When Firefly is not served at the root path, the webhook index page breaks, not listing the webhooks.
I added a "." to the URL, like other components do.
Since the solution was simple, I did not open an issue first. 
@JC5
> Fix webhook index page when Firefly is not served at root

- app/Models/Transaction.php
Laravel defers to PDO & the underlying database as to what type decimals are cast as. When using sqlite text that match a float will be returned as a float, while mySql always returns a string for a decimal. This leads to crashes with sqlite while trying to import tranansactions. (It does not happen every transaction, only when the balance{before,after} coming from the database is floatable)
`FireflyIII\Support\Models\AccountBalanceCalculator::getLatestBalance(): Return value must be of type string, float returned.`
Fixes: #9458
I figured this out a few days ago, and finally had the time to PR, and saw someone beat me to report the issue. This should be a better & more permanent fix than typecasting the return value, which i only saw you implemented after i opened the pr.
This PR fixes …
> Transaction Model: explicitly cast decimal to string

- app/Services/Internal/Update/JournalUpdateService.php
This PR fixes issue #9487.
- This PR fixes an issue where `foreign_amount` and `foreign_currency_id` were not being set for destination transactions during foreign currency transfer updates. This caused balance inconsistencies and errors such as `Sum of journal #%d is not zero` after restarting Firefly III. The changes ensure these fields are correctly populated to prevent such issues.
@JC5
> fix: set dest foreign_amount and foreign_currency_id for foreign transfers

- app/Console/Commands/Integrity/ReportSum.php
This PR fixes issue #9482.
- Updated the transaction sum calculation to account for both `amount` and `foreign_amount` fields. This ensures that transfers involving foreign currencies are correctly included in the `reportSum` check.
@JC5
> fix: include foreign_amount in transaction sum calculation

- database/seeders/TransactionCurrencySeeder.php
- Adding SEK
- Adding NOK
- Adding ISK
Most of the nordic countries in Europe have some different flavours of 'Krona'. I only found the Danish krone in the repo so I added the Swedish, Norwegian and Icelandic to be more inclusive. This feels inline with the currency exchange you are currently implementing.
References:
- https://sv.wikipedia.org/wiki/Svensk_krona
- https://no.wikipedia.org/wiki/Norsk_krone
- https://is.wikipedia.org/wiki/%C3%8Dslensk_kr%C3%B3na
@JC5
> Feature nordic currencies

- .dockerignore
This PR fixes issue #9833.
- This PR removes the Procfile from the built docker image. The Procfile is heroku-specific, causing issues on platforms which respect it when specifying processes to run for docker image or dockerfile based deploys.
@JC5
> fix: ignore the Procfile when building the docker image

- app/TransactionRules/Expressions/ActionExpressionLanguageProvider.php
- Add support for PHP function `strpos` in expressions
@JC5
> Add support for PHP function `strpos` in expressions

- app/Support/Cronjobs/UpdateCheckCronjob.php
If the update check cron is disabled or run more often than once a week consider the cron run succesfull.
This PR fixes issue #10038.
- Mark update-check cron as succeeded if update check is disabled
- Mark update-check cron as succeeded if update check run too frequently
@JC5
> update check: consider cron succesfull when disabled or too frequent

- resources/views/reports/category/partials/avg-income.twig
use correct translation key for category report income table. 
The key already exists in the translations, but the incorrect one was used:
```
'spent_average'  => 'Spent (average)',
'income_average' => 'Income (average)',
```
> use correct translation key for category report income table
